#!/usr/bin/env bash
# This script does:
# 	Creates a file "/var/run/myscript.pid" containingthe script PID.
#	Displays "To infinity and beyond" indefinitely
#	Displays "I hate the kill command" when receiving SIGTERM signal
#	Displays "Y U no love me?!" when receiving SIGINT signal.
#	Deletes the file /var/run/myscript.pid and terminates when receiving a SIGQUIT or SSIGTERM.

terminate() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminate' SIGTERM
	trap 'terminate' SIGQUIT
done
