#!/usr/bin/env bash
# This script displays "To infinity and back" indefinitely with a
#+ sleep 3 in between each iteration. and also displays "I am invincible!!!"

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
