#!/usr/bin/env bash
# This script displays "Best School", "bad luck" and "good luck"

i=0
while [ $i -lt 10 ]
do
	if [ $i = 3 ]
	then
		echo "bad luck"
	elif [ $i = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
