#!/usr/bin/env bash
# Fixes a web server to run Nginx as nginx user on port 8080.

# Set a user in the config
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx.conf

# Replace port 80 with 8080 in the sites-available cn=onfig
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Give read and write permission to owner on config file
sudo chmod 644 /etc/nginx/nginx.conf

# Kill apache in case it's intefering
sudo pkill apache2

# Start nginx service with the new user
sudo -u nginx service nginx start
