#!/usr/bin/env bash
# Fix a web server to run Nginx as nginx user listenning on port 8080
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx start
